#!/bin/bash
# =============================================================================
# generate_monolith.sh - Generate JoltContinuations.tla from modular tla/*.tla
# =============================================================================
# This script concatenates the modular TLA+ specification files into a single
# monolithic file for easier external review and distribution.
#
# The canonical source is tla/*.tla - edit there, then regenerate.
#
# Usage: ./scripts/generate_monolith.sh
# Output: JoltContinuations.tla (root directory)
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
OUTPUT="$REPO_ROOT/JoltContinuations.tla"
TLA_DIR="$REPO_ROOT/tla"

echo "=== Generating Monolithic TLA+ Specification ==="
echo "Source: $TLA_DIR/*.tla"
echo "Output: $OUTPUT"
echo ""

# Module dependency order (topological sort)
MODULES=(
    "Types"
    "Encodings"
    "Hash"
    "SMT"
    "SMTOps"
    "VMState"
    "Transcript"
    "Continuations"
    "Registry"
    "Wrapper"
    "JoltSpec"
    "Invariants"
    "MC_Jolt"
)

# Create header
cat > "$OUTPUT" << 'EOF'
(****************************************************************************)
(* JoltContinuations.tla - Monolithic Specification (AUTO-GENERATED)        *)
(*                                                                          *)
(* DO NOT EDIT THIS FILE DIRECTLY!                                          *)
(*                                                                          *)
(* This file is auto-generated from the modular specifications in tla/*.tla *)
(* Edit the source modules, then run: ./scripts/generate_monolith.sh        *)
(*                                                                          *)
(* Canonical entrypoint for CI: tla/MC_Jolt.tla                             *)
(* This file is for external review and distribution only.                  *)
(*                                                                          *)
(* Author: Charles Hoskinson                                                *)
(* Copyright: 2026 Charles Hoskinson                                        *)
(* License: Apache 2.0                                                      *)
(* Part of: https://github.com/CharlesHoskinson/jolt-tla                    *)
(****************************************************************************)

EOF

# Add generation timestamp
echo "(* Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC') *)" >> "$OUTPUT"
echo "(* Source modules: ${MODULES[*]} *)" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Extract and concatenate module contents
echo "Processing modules..."
for module in "${MODULES[@]}"; do
    MODULE_FILE="$TLA_DIR/$module.tla"
    if [[ -f "$MODULE_FILE" ]]; then
        echo "  Processing: $module.tla"

        # Add module separator comment
        echo "" >> "$OUTPUT"
        echo "(***************************************************************************)" >> "$OUTPUT"
        echo "(* BEGIN MODULE: $module                                                   *)" >> "$OUTPUT"
        echo "(***************************************************************************)" >> "$OUTPUT"
        echo "" >> "$OUTPUT"

        # Append module content (excluding the ---- MODULE line and ==== end marker)
        # Keep all content between module header and footer
        sed -n '/^---- MODULE/,/^====$/p' "$MODULE_FILE" | \
            sed '1d;$d' >> "$OUTPUT"

        echo "" >> "$OUTPUT"
        echo "(* END MODULE: $module *)" >> "$OUTPUT"
    else
        echo "  WARNING: $MODULE_FILE not found, skipping"
    fi
done

# Add final module wrapper
cat >> "$OUTPUT" << 'EOF'

(****************************************************************************)
(* END OF AUTO-GENERATED MONOLITHIC SPECIFICATION                           *)
(****************************************************************************)

---- MODULE JoltContinuations ----
(* This module imports all definitions from the concatenated content above *)
(* For model checking, use tla/MC_Jolt.tla with Jolt.cfg instead           *)

EXTENDS Sequences, Naturals, FiniteSets, TLC

(* Re-export key definitions for external use *)
(* See individual module sections above for full definitions *)

====
EOF

echo ""
echo "Generated: $OUTPUT"
echo "Lines: $(wc -l < "$OUTPUT")"
echo ""
echo "Note: This is a distribution artifact. For development and CI,"
echo "use the modular specification: tla/MC_Jolt.tla"
